In [1]:
import tensorflow as tf

2022-09-15 18:25:20.114330: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-15 18:25:20.114371: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
x = tf.constant([1,2,3])
y = tf.constant([5,6,7])

2022-09-15 18:25:47.819232: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-09-15 18:25:47.819260: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-09-15 18:25:47.819285: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (tomskopfbahnhof): /proc/driver/nvidia/version does not exist
2022-09-15 18:25:47.819589: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
x = tf.expand_dims(x, axis=-1)
x = tf.repeat(x, repeats=x.shape[0], axis=1)


In [4]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)>

In [27]:
y = tf.constant([5,6,7])
y = tf.expand_dims(y, axis=0)


In [28]:
y

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[5, 6, 7]], dtype=int32)>

In [29]:
y = tf.repeat(y, repeats=y.shape[1], axis=0)

In [30]:
y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[5, 6, 7],
       [5, 6, 7],
       [5, 6, 7]], dtype=int32)>

In [31]:
y = tf.constant([[1,2,3],[4,5,6]])
y_d = tf.constant([1,2,3])

In [32]:
y / y_d

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])>