In [1]:
import tensorflow as tf
import numpy as np

2022-09-14 22:16:07.013993: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-14 22:16:07.014036: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [31]:
x = tf.constant([1,2,3])
y = tf.constant([2,3,4])

In [32]:
x = tf.expand_dims(x, axis=-1)

In [35]:
tf.repeat(x, repeats=3,axis=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]], dtype=int32)>

In [37]:
y = tf.expand_dims(y, axis=0)

In [39]:
tf.repeat(y, repeats=3,axis=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]], dtype=int32)>